{
  pkgs,
  lib,
  versions,
  pythonOverrides,
  gpuSupport ? "none", # "none", "cuda", "rocm", "xpu"
}:
let
  useCuda = gpuSupport == "cuda" && pkgs.stdenv.isLinux;
  useRocm = gpuSupport == "rocm" && pkgs.stdenv.isLinux;
  useXpu = gpuSupport == "xpu" && pkgs.stdenv.isLinux && pkgs.stdenv.hostPlatform.isx86_64;

  # Intel XPU runtime libraries (Level Zero loader, Intel compute-runtime, OpenCL ICD)
  # Bundled as a fallback when /run/opengl-driver/lib isn't available (non-NixOS Linux,
  # Docker images without host driver pass-through). On NixOS, the launcher prefers
  # system-provided libs via /run/opengl-driver/lib (populated by hardware.graphics.extraPackages)
  # to keep the userland ICD in sync with the kernel DRM driver.
  xpuRuntimeLibs = lib.optionals useXpu [
    pkgs.level-zero
    pkgs.intel-compute-runtime
    pkgs.ocl-icd
  ];

  python = pkgs.python312.override { packageOverrides = pythonOverrides; };

  vendored = import ./vendored-packages.nix { inherit pkgs python versions; };

  # Template input files (images, audio, etc. for workflow templates)
  templateInputs = import ./template-inputs.nix { inherit pkgs; };

  # Bundled fonts for custom nodes that require font files
  # This provides a pure Nix solution for nodes like ComfyUI_Comfyroll_CustomNodes
  # that expect fonts at hardcoded paths like /usr/share/fonts/truetype
  bundledFonts = pkgs.symlinkJoin {
    name = "comfyui-fonts";
    paths = [
      pkgs.dejavu_fonts
      pkgs.liberation_ttf
      pkgs.noto-fonts
      pkgs.roboto
    ];
    postBuild = ''
      # Create a flat directory with all TTF files for easy access
      mkdir -p $out/ttf
      find $out/share/fonts -name "*.ttf" -exec ln -sf {} $out/ttf/ \; 2>/dev/null || true
      find $out/share/fonts -name "*.TTF" -exec ln -sf {} $out/ttf/ \; 2>/dev/null || true
    '';
  };

  # Import custom nodes for bundling
  customNodes = import ./custom-nodes.nix {
    inherit
      pkgs
      lib
      python
      versions
      ;
  };

  comfyuiSrcRaw = pkgs.fetchFromGitHub {
    owner = "Comfy-Org";
    repo = "ComfyUI";
    rev = versions.comfyui.rev;
    hash = versions.comfyui.hash;
  };

  comfyuiSrc = pkgs.applyPatches {
    src = comfyuiSrcRaw;
    patches = [
      ../nix/patches/comfyui-ltxvideo-compat.patch
      ../nix/patches/comfyui-cpu-fallback.patch
    ];
  };

  modelDownloaderDir = builtins.path {
    path = ../src/custom_nodes/model_downloader;
    name = "comfyui-model-downloader";
  };

  # Pip constraints to prevent conflicts with Nix-provided packages
  pipConstraints = pkgs.writeText "pip-constraints.txt" ''
    # Auto-generated by comfyui-nix
    # Prevents pip/uv from overwriting Nix-provided packages with incompatible versions
    huggingface-hub<1.0
    transformers>=4.50.3
    torch>=2.0.0
    torchvision>=0.15.0
    numpy>=1.25.0
    pillow>=9.0.0
    safetensors>=0.4.2
    aiohttp>=3.11.8
    yarl>=1.18.0
    SQLAlchemy>=2.0.0
    av>=16.0.0
    simpleeval>=1.0.0
    # Prevent ComfyUI-Manager from trying to "restore" vendored packages
    # Use exact pinning to ensure reproducibility
    comfyui-frontend-package==${versions.vendored.frontendPackage.version}
    comfyui-workflow-templates==${versions.vendored.workflowTemplates.version}
    comfyui-embedded-docs==${versions.vendored.embeddedDocs.version}
    comfyui-manager==${versions.vendored.manager.version}
    comfy-kitchen==${versions.vendored.comfyKitchen.version}
    comfy-aimdo==${versions.vendored.comfyAimdo.version}
    gradio-client==${versions.vendored.gradioClient.version}
    gradio==${versions.vendored.gradio.version}
    sageattention==${versions.vendored.sageattention.version}
  '';

  # Default ComfyUI-Manager configuration
  managerConfig = pkgs.writeText "comfyui-manager-config.ini" ''
    # ComfyUI-Manager configuration
    # Generated by comfyui-nix flake
    #
    # security_level: strong | normal | normal- | weak
    # network_mode: public | private | offline | personal_cloud
    #
    # personal_cloud mode relaxes security for trusted environments
    # (e.g., running on your own machine with --listen for network access)

    [default]
    security_level = normal
    network_mode = personal_cloud
  '';

  pythonRuntime = python.withPackages (
    ps:
    let
      available = pkg: lib.meta.availableOn pkgs.stdenv.hostPlatform pkg;
      # Core ComfyUI dependencies
      base = with ps; [
        pillow
        numpy
        einops
        transformers
        tokenizers
        sentencepiece
        safetensors
        aiohttp
        yarl
        pyyaml
        requests
        scipy
        tqdm
        psutil
        alembic
        sqlalchemy
        filelock
        av
        blake3
        pydantic-settings
        simpleeval
      ];
      # ComfyUI Manager and common custom node dependencies
      extras =
        with ps;
        [
          pip # Required for comfyui-manager security check
          uv # Required for comfyui-manager package management
          chardet # Required for comfyui-manager to read requirements.txt files
          pygithub # Required for comfyui-manager GitHub integration
          typer # Required for comfyui-manager CLI
          matrix-nio # Optional: enables ComfyUI-Manager matrix sharing feature
          opencv4 # Required by many custom nodes for image processing (cv2)
          imageio-ffmpeg # Required by VideoHelperSuite and other video nodes
          # Impact Pack dependencies
          scikit-image # Image processing (skimage)
          piexif # EXIF metadata handling
          matplotlib # Plotting and visualization
          dill # Extended pickling
          segment-anything # Meta AI SAM model
          sam2 # Meta AI SAM 2 model
          # Impact Subpack dependencies
          ultralytics # YOLO object detection (for UltralyticsDetectorProvider)
          # KJNodes dependencies
          mss # Screen capture
          # General ML utilities
          accelerate # HuggingFace Accelerate for distributed training/inference
          # ComfyUI-GGUF dependencies
          gguf # GGUF file format support
          protobuf # Required for GGUF tokenizer support
          # LTXVideo dependencies
          diffusers # Diffusion models
          huggingface-hub # HuggingFace Hub
          timm # PyTorch Image Models
          # Florence2 dependencies
          peft # Parameter-efficient fine-tuning
          # MMAudio dependencies
          librosa # Audio processing
          torchdiffeq # Differential equations solver
          omegaconf # Configuration management
          open-clip-torch # OpenCLIP
          ftfy # Text encoding fixes
          # PuLID dependencies
          onnxruntime # ONNX runtime
        ]
        ++ [ ps."color-matcher" ] # Color matching (hyphenated name needs quoting)
        # Common custom-node deps ("it just works" set)
        ++ lib.optionals (ps ? ollama && available ps.ollama) [ ps.ollama ]
        ++ lib.optionals (ps ? "pytorch-lightning" && available ps."pytorch-lightning") [
          ps."pytorch-lightning"
        ]
        ++ lib.optionals (ps ? "google-genai" && available ps."google-genai") [
          ps."google-genai"
        ]
        ++ lib.optionals (ps ? "google-generativeai" && available ps."google-generativeai") [
          ps."google-generativeai"
        ];
      # torch is overridden at the base level in python-overrides.nix when when gpuSupport="cuda|rocm"
      # so ps.torch is already CUDA/ROCm-enabled when building with CUDA/ROCm support
      torchPackages = lib.optionals (ps ? torch && available ps.torch) [ ps.torch ];
      optionals =
        torchPackages
        ++ lib.optionals (ps ? torchvision && available ps.torchvision) [ ps.torchvision ]
        ++ lib.optionals (ps ? torchaudio && available ps.torchaudio) [ ps.torchaudio ]
        ++ lib.optionals (ps ? torchsde && available ps.torchsde) [ ps.torchsde ]
        # kornia excluded on macOS and aarch64-linux: kornia-rs has Cargo/badPlatforms issues
        # See: https://github.com/NixOS/nixpkgs/issues/458799
        ++ lib.optionals (
          pkgs.stdenv.isLinux && pkgs.stdenv.isx86_64 && ps ? kornia && available ps.kornia
        ) [ ps.kornia ]
        ++ lib.optionals (ps ? pydantic && available ps.pydantic) [ ps.pydantic ]
        ++ lib.optionals (ps ? spandrel && available ps.spandrel) [ ps.spandrel ]
        ++ lib.optionals (ps ? pyopengl && available ps.pyopengl) [ ps.pyopengl ]
        ++ lib.optionals (ps ? glfw && available ps.glfw) [ ps.glfw ]
        ++ lib.optionals (ps ? gitpython && available ps.gitpython) [ ps.gitpython ]
        ++ lib.optionals (ps ? toml && available ps.toml) [ ps.toml ]
        ++ lib.optionals (ps ? rich && available ps.rich) [ ps.rich ]
        ++ lib.optionals (ps ? "comfy-cli" && available ps."comfy-cli") [ ps."comfy-cli" ]
        # Linux-only packages (CUDA dependencies)
        ++ lib.optionals (pkgs.stdenv.isLinux && ps ? bitsandbytes) [ ps.bitsandbytes ]
        ++ lib.optionals (pkgs.stdenv.isLinux && ps ? xformers) [ ps.xformers ]
        ++ lib.optionals (pkgs.stdenv.isLinux && ps ? triton && available ps.triton) [ ps.triton ]
        # Face analysis packages - work on all platforms (insightface override removes mxnet)
        ++ lib.optionals (ps ? insightface) [ ps.insightface ]
        ++ lib.optionals (ps ? facexlib) [ ps.facexlib ]
        ++ [
          vendored.comfyuiFrontendPackage
          vendored.comfyuiWorkflowTemplates
          vendored.comfyuiEmbeddedDocs
          vendored.comfyuiManager
          vendored.comfyKitchen
          vendored.comfyAimdo
          vendored.gradioClient
          vendored.gradio
          vendored.sageattention
        ];
    in
    base ++ extras ++ optionals
  );

  frontendRoot = "${pythonRuntime}/${python.sitePackages}/comfyui_frontend_package/static";

  # NOTE: Some custom nodes (and some Python wheels) dlopen GUI-related libs at runtime
  # (e.g. OpenCV highgui / Qt platform plugins). Ensure common X11 libs are discoverable.
  libPath = lib.makeLibraryPath (
    [
      pkgs.stdenv.cc.cc.lib
      pkgs.glib
      pkgs.libGL
      # X11 / XCB runtime libs (fixes: libxcb.so.1 not found)
      pkgs.xorg.libxcb
      pkgs.xorg.libX11
      pkgs.xorg.libXext
      pkgs.xorg.libXrender
      pkgs.xorg.libXfixes
      pkgs.xorg.libXi
      pkgs.xorg.libXrandr
      pkgs.xorg.libXcursor
      pkgs.xorg.libXcomposite
      pkgs.xorg.libXdamage
      pkgs.xorg.libXau
      pkgs.xorg.libXdmcp
      pkgs.xorg.libSM
      pkgs.xorg.libICE
      pkgs.libxkbcommon
    ]
    # XPU runtime libs (Level Zero, Intel compute-runtime, OpenCL ICD) — fallback
    # when /run/opengl-driver/lib isn't available. Launcher prefers system libs.
    ++ xpuRuntimeLibs
  );

  # Platform-specific default data directory
  # macOS: ~/Library/Application Support/comfy-ui (Apple convention)
  # Linux: ~/.config/comfy-ui (XDG convention)
  defaultDataDir =
    if pkgs.stdenv.isDarwin then
      "$HOME/Library/Application Support/comfy-ui"
    else
      "$HOME/.config/comfy-ui";

  # Platform-specific library path setup
  libraryPathSetup =
    if pkgs.stdenv.isDarwin then
      ''
        # macOS: Set DYLD_LIBRARY_PATH for dynamic libraries
        export DYLD_LIBRARY_PATH="${libPath}''${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
      ''
    else
      ''
        # Linux: Set LD_LIBRARY_PATH for dynamic libraries
        # Order matters: system driver libs (/run/opengl-driver/lib on NixOS) take
        # precedence over Nix-bundled libs so userland ICDs stay in sync with the
        # kernel DRM driver. This covers NVIDIA (CUDA), AMD (ROCm), and Intel (XPU).
        export LD_LIBRARY_PATH="${libPath}''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

        if [[ -d "/run/opengl-driver/lib" ]]; then
          export LD_LIBRARY_PATH="/run/opengl-driver/lib:$LD_LIBRARY_PATH"
        fi
      '';

  # Platform-specific browser command
  browserCommand = if pkgs.stdenv.isDarwin then "/usr/bin/open" else "xdg-open";

  # Minimal launcher using writeShellApplication (Nix best practice)
  comfyUiLauncher = pkgs.writeShellApplication {
    name = "comfy-ui";
    runtimeInputs = [
      pkgs.coreutils
      pkgs.findutils
      pkgs.gnused
      pkgs.git # Required for ComfyUI Manager to clone custom nodes
    ]
    ++ lib.optionals (!pkgs.stdenv.isDarwin) [
      pkgs.xdg-utils # Provides xdg-open for --open flag on Linux
    ];
    text = ''
            # Increase file descriptor limit for aiohttp/grpc DNS resolver
            # macOS default (256) is too low; Linux (1024) may also be insufficient
            # ComfyUI-Manager's concurrent HTTP requests with c-ares DNS can exhaust FDs
            ulimit -n 10240 2>/dev/null || true

            # Parse arguments - extract --base-directory, --open, --port, pass rest to ComfyUI
            BASE_DIR="''${COMFY_USER_DIR:-${defaultDataDir}}"
            OPEN_BROWSER=false
            PORT=8188
            COMFY_ARGS=()

            while [[ $# -gt 0 ]]; do
              case "$1" in
                --base-directory=*)
                  BASE_DIR="''${1#*=}"
                  shift
                  ;;
                --base-directory)
                  BASE_DIR="$2"
                  shift 2
                  ;;
                --port=*)
                  PORT="''${1#*=}"
                  COMFY_ARGS+=("$1")
                  shift
                  ;;
                --port)
                  PORT="$2"
                  COMFY_ARGS+=("$1" "$2")
                  shift 2
                  ;;
                --open)
                  OPEN_BROWSER=true
                  shift
                  ;;
                *)
                  COMFY_ARGS+=("$1")
                  shift
                  ;;
              esac
            done

            # Expand ~ in BASE_DIR (handles both ~/path and ~user/path)
            BASE_DIR="''${BASE_DIR/#\~/$HOME}"

            # Create directory structure (idempotent)
            mkdir -p "$BASE_DIR"/{models,output,input,user,custom_nodes,temp,web}
            mkdir -p "$BASE_DIR/web/extensions"
            mkdir -p "$BASE_DIR/models"/{checkpoints,loras,vae,controlnet,embeddings,upscale_models,clip,clip_vision,diffusion_models,text_encoders,unet,configs,diffusers,vae_approx,gligen,hypernetworks,photomaker,style_models,classifiers,t2i_adapter}

            # Expose base dir for custom nodes that need a writable location (Nix store is read-only)
            export COMFYUI_BASE_DIR="$BASE_DIR"

            # Link template input files for workflow templates
            # These are pre-fetched at Nix build time for pure, reproducible builds
            if [[ -d "${templateInputs}/input" ]]; then
              for input_file in "${templateInputs}"/input/*; do
                if [[ -e "$input_file" ]]; then
                  filename=$(basename "$input_file")
                  target="$BASE_DIR/input/$filename"
                  # Only create symlink if file doesn't exist (don't overwrite user files)
                  if [[ ! -e "$target" ]]; then
                    ln -sf "$input_file" "$target"
                  fi
                fi
              done
            fi

            # Create fonts directory with bundled fonts for custom nodes
            # This provides fonts for nodes like ComfyUI_Comfyroll_CustomNodes that expect
            # fonts at hardcoded paths like /usr/share/fonts/truetype (which doesn't exist on NixOS)
            FONTS_DIR="$BASE_DIR/fonts"
            mkdir -p "$FONTS_DIR"
            # Symlink bundled TTF fonts (only if not already linked)
            for font_file in "${bundledFonts}"/ttf/*.ttf "${bundledFonts}"/ttf/*.TTF; do
              if [[ -e "$font_file" ]]; then
                filename=$(basename "$font_file")
                target="$FONTS_DIR/$filename"
                if [[ ! -e "$target" ]]; then
                  ln -sf "$font_file" "$target"
                fi
              fi
            done

            # Patch custom nodes that use hardcoded font paths for NixOS compatibility
            # ComfyUI_Comfyroll_CustomNodes: patch /usr/share/fonts/truetype -> $BASE_DIR/fonts
            COMFYROLL_FONT_FILE="$BASE_DIR/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/nodes_graphics_text.py"
            if [[ -f "$COMFYROLL_FONT_FILE" ]]; then
              if grep -q '"/usr/share/fonts/truetype"' "$COMFYROLL_FONT_FILE" 2>/dev/null; then
                sed -i "s|\"/usr/share/fonts/truetype\"|\"$FONTS_DIR\"|g" "$COMFYROLL_FONT_FILE"
                echo "Patched ComfyUI_Comfyroll_CustomNodes for NixOS font compatibility"
              fi
            fi

            # comfyui-custom-scripts (pysssss): avoid writing into the read-only Nix store.
            # It computes ComfyUI's web extension dir from PromptServer's file path (in /nix/store)
            # and then attempts to mkdir there at import time.
            PYSSSSS_FILE="$BASE_DIR/custom_nodes/comfyui-custom-scripts/pysssss.py"
            if [[ -f "$PYSSSSS_FILE" ]]; then
              if grep -q 'get_comfy_dir("web/extensions/pysssss")' "$PYSSSSS_FILE" 2>/dev/null; then
                sed -i 's|dir = get_comfy_dir("web/extensions/pysssss")|dir = os.path.join(os.environ.get("COMFYUI_BASE_DIR", get_comfy_dir()), "web/extensions/pysssss")|g' "$PYSSSSS_FILE"
                echo "Patched comfyui-custom-scripts for NixOS read-only store compatibility"
              fi
            fi

            # Link our bundled custom nodes
            # Remove stale directories if they exist but aren't symlinks
            for node_dir in "model_downloader" "ComfyUI-Impact-Pack" "rgthree-comfy" "ComfyUI-KJNodes" "ComfyUI-GGUF" "ComfyUI-LTXVideo" "ComfyUI-Florence2" "ComfyUI_bitsandbytes_NF4" "x-flux-comfyui" "ComfyUI-MMAudio" "PuLID_ComfyUI" "ComfyUI-WanVideoWrapper"; do
              if [[ -e "$BASE_DIR/custom_nodes/$node_dir" && ! -L "$BASE_DIR/custom_nodes/$node_dir" ]]; then
                rm -rf "$BASE_DIR/custom_nodes/$node_dir"
              fi
            done

            # On macOS, remove Linux-only nodes if they were linked previously
            # Note: PuLID now works on macOS via CoreML (insightface override removes mxnet dependency)
            if [[ "$(uname)" == "Darwin" ]]; then
              rm -f "$BASE_DIR/custom_nodes/ComfyUI_bitsandbytes_NF4" 2>/dev/null || true
            fi

            # Clean up stale read-only web extension directories (from Nix store)
            if [[ -d "$BASE_DIR/web/extensions" ]]; then
              find "$BASE_DIR/web/extensions" -maxdepth 1 -type d ! -writable -exec rm -rf {} \; 2>/dev/null || true
            fi

            # Link bundled nodes (always update symlinks to pick up new Nix store paths)
            ln -sfn "${modelDownloaderDir}" "$BASE_DIR/custom_nodes/model_downloader"
            ln -sfn "${customNodes.impact-pack}" "$BASE_DIR/custom_nodes/ComfyUI-Impact-Pack"
            ln -sfn "${customNodes.rgthree-comfy}" "$BASE_DIR/custom_nodes/rgthree-comfy"
            ln -sfn "${customNodes.kjnodes}" "$BASE_DIR/custom_nodes/ComfyUI-KJNodes"
            ln -sfn "${customNodes.gguf}" "$BASE_DIR/custom_nodes/ComfyUI-GGUF"
            ln -sfn "${customNodes.ltxvideo}" "$BASE_DIR/custom_nodes/ComfyUI-LTXVideo"
            ln -sfn "${customNodes.florence2}" "$BASE_DIR/custom_nodes/ComfyUI-Florence2"
            # bitsandbytes requires CUDA (Linux-only)
            if [[ "$(uname)" != "Darwin" ]]; then
              ln -sfn "${customNodes.bitsandbytes-nf4}" "$BASE_DIR/custom_nodes/ComfyUI_bitsandbytes_NF4"
            fi
            ln -sfn "${customNodes.x-flux}" "$BASE_DIR/custom_nodes/x-flux-comfyui"
            ln -sfn "${customNodes.mmaudio}" "$BASE_DIR/custom_nodes/ComfyUI-MMAudio"
            # PuLID - face ID for consistent face generation
            # Works on all platforms: Linux uses CUDA, macOS uses CoreML via onnxruntime
            ln -sfn "${customNodes.pulid}" "$BASE_DIR/custom_nodes/PuLID_ComfyUI"
            ln -sfn "${customNodes.wanvideo}" "$BASE_DIR/custom_nodes/ComfyUI-WanVideoWrapper"

            # Create default ComfyUI-Manager config if it doesn't exist
            # Note: Manager moved config from user/default/ComfyUI-Manager to user/__manager
            MANAGER_CONFIG_DIR="$BASE_DIR/user/__manager"
            MANAGER_CONFIG="$MANAGER_CONFIG_DIR/config.ini"
            if [[ ! -e "$MANAGER_CONFIG" ]]; then
              mkdir -p "$MANAGER_CONFIG_DIR"
              cp "${managerConfig}" "$MANAGER_CONFIG"
              echo "Created default ComfyUI-Manager config at $MANAGER_CONFIG"
            fi

            # Set platform-specific library paths for GPU support
            ${libraryPathSetup}

            # Create a mutable PEP 405 venv structure for ComfyUI-Manager package installs
            # This allows both pip and uv to install packages to a writable location
            # while keeping the Nix store read-only
            VENV_DIR="$BASE_DIR/.venv"
            SITE_PACKAGES="$VENV_DIR/lib/python3.12/site-packages"
            mkdir -p "$SITE_PACKAGES"
            mkdir -p "$VENV_DIR/bin"

            # Create pyvenv.cfg if it doesn't exist (required for PEP 405 compliance)
            if [[ ! -e "$VENV_DIR/pyvenv.cfg" ]]; then
              cat > "$VENV_DIR/pyvenv.cfg" << PYVENV
      home = ${pythonRuntime}/bin
      include-system-site-packages = true
      version = 3.12.9
      PYVENV
            fi

            # Symlink Python executable into venv bin (some tools expect this)
            if [[ ! -e "$VENV_DIR/bin/python" ]]; then
              ln -sf "${pythonRuntime}/bin/python" "$VENV_DIR/bin/python"
              ln -sf "${pythonRuntime}/bin/python3" "$VENV_DIR/bin/python3"
              ln -sf "${pythonRuntime}/bin/python3.12" "$VENV_DIR/bin/python3.12"
            fi

            # Set VIRTUAL_ENV so uv installs to our mutable venv instead of Nix store
            export VIRTUAL_ENV="$VENV_DIR"

            # Also set PIP_TARGET for pip compatibility
            export PIP_TARGET="$SITE_PACKAGES"

            # Ensure Nix-provided packages take precedence over anything installed by the Manager.
            # Some setups (e.g. a long-lived ~/AI directory) may already have pip-installed
            # torch/numpy/etc in $VENV_DIR, which can conflict with our pinned, known-good stack.
            #
            # Default behavior: append the venv site-packages to sys.path (so it only fills gaps).
            # If you *really* want the venv to override Nix packages, set:
            #   COMFY_VENV_PRECEDENCE=prefer-venv
            SITE_CUSTOMIZE_DIR="$BASE_DIR/.comfyui_sitecustomize"
            mkdir -p "$SITE_CUSTOMIZE_DIR"
            # Create a tiny sitecustomize.py. We use this (instead of putting the venv
            # site-packages directly on PYTHONPATH) so the venv only fills missing deps by default.
            {
              printf '%s\n' \
                'import os' \
                'import site' \
                'import sys' \
                ' ' \
                'precedence = os.environ.get("COMFY_VENV_PRECEDENCE", "")' \
                'venv = os.environ.get("VIRTUAL_ENV")' \
                'if venv:' \
                '    sp = os.path.join(venv, "lib", f"python{sys.version_info.major}.{sys.version_info.minor}", "site-packages")' \
                '    if os.path.isdir(sp):' \
                '        if precedence == "prefer-venv":' \
                '            # Make venv take priority (old behavior)' \
                '            sys.path.insert(0, sp)' \
                '        else:' \
                '            # Default: add venv at the end so Nix packages win' \
                '            site.addsitedir(sp)'
            } > "$SITE_CUSTOMIZE_DIR/sitecustomize.py"

            export PYTHONPATH="$SITE_CUSTOMIZE_DIR''${PYTHONPATH:+:$PYTHONPATH}"

            # mergekit (used by lora-merger-comfyui) uses pydantic.create_model with torch.Tensor
            # without allowing arbitrary types, which crashes under pydantic v2.
            MERGEKIT_EASY_DEFINE=$(find "$VENV_DIR" -path '*/site-packages/mergekit/merge_methods/easy_define.py' -print -quit 2>/dev/null || true)
            if [[ -n "$MERGEKIT_EASY_DEFINE" ]]; then
              if ! grep -q 'arbitrary_types_allowed=True' "$MERGEKIT_EASY_DEFINE" 2>/dev/null; then
                # Patch:
                #   create_model(..., __base__=Task[torch.Tensor], **tt_fields)
                # ->create_model(..., __base__=Task[torch.Tensor], __config__=pydantic.ConfigDict(arbitrary_types_allowed=True), **tt_fields)
                perl -pi -e 's/pydantic\.create_model\(tt_name, __base__=Task\[torch\.Tensor\], \*\*tt_fields\)/pydantic.create_model(tt_name, __base__=Task[torch.Tensor], __config__=pydantic.ConfigDict(arbitrary_types_allowed=True), **tt_fields)/g' \
                  "$MERGEKIT_EASY_DEFINE" || true
              fi
            fi

            # Prevent pip/uv from installing packages that conflict with Nix-provided ones
            export PIP_CONSTRAINT="${pipConstraints}"
            export UV_CONSTRAINT="${pipConstraints}"

            # Set model path for custom nodes that check this env var
            # (prevents them from trying to write to the read-only Nix store)
            export COMFYUI_MODEL_PATH="$BASE_DIR/models"

            # Redirect PyTorch hub downloads to data directory
            # This prevents attempts to write to the read-only Nix store
            export TORCH_HOME="$BASE_DIR/.cache/torch"
            mkdir -p "$TORCH_HOME"

            # Redirect HuggingFace cache to data directory for model downloads
            export HF_HOME="$BASE_DIR/.cache/huggingface"
            mkdir -p "$HF_HOME"

            # Redirect facexlib model downloads to data directory
            # (facexlib is patched to respect this env var)
            export FACEXLIB_MODELPATH="$BASE_DIR/.cache/facexlib"
            mkdir -p "$FACEXLIB_MODELPATH/facexlib/weights"

      ${lib.optionalString useCuda ''
        # =====================================================================
        # NVIDIA Blackwell / CUDA 12.x compatibility
        # =====================================================================
        # ComfyUI enables cudaMallocAsync automatically for CUDA builds unless a
        # device is explicitly blacklisted. On Blackwell cards with the current
        # cu128 PyTorch wheels, users have reported generation-time crashes and
        # ComfyUI's own warning recommends --disable-cuda-malloc for allocator
        # errors. Disable it automatically for RTX 50/Blackwell unless the user
        # already selected an allocator mode in extraArgs.
        case " ''${COMFY_ARGS[*]} " in
          *" --disable-cuda-malloc "*|*" --cuda-malloc "*)
            ;;
          *)
            detect_nvidia_gpus() {
              if command -v nvidia-smi >/dev/null 2>&1; then
                nvidia-smi -L 2>/dev/null && return 0
              fi
              for nvidia_smi in /run/current-system/sw/bin/nvidia-smi /run/opengl-driver/bin/nvidia-smi; do
                if [[ -x "$nvidia_smi" ]]; then
                  "$nvidia_smi" -L 2>/dev/null && return 0
                fi
              done
              for gpu_info in /proc/driver/nvidia/gpus/*/information; do
                if [[ -r "$gpu_info" ]]; then
                  grep -E '^Model:' "$gpu_info" 2>/dev/null || true
                fi
              done
              return 0
            }

            if detect_nvidia_gpus | grep -Eiq 'GeForce RTX 50[0-9]{2}|RTX PRO .*Blackwell|Blackwell|NVIDIA B[0-9]{3}'; then
              echo "Detected NVIDIA Blackwell GPU; adding --disable-cuda-malloc for stability."
              COMFY_ARGS+=("--disable-cuda-malloc")
            fi
            ;;
        esac
      ''}

      ${lib.optionalString useXpu ''
        # =====================================================================
        # Intel XPU (oneAPI / SYCL) runtime setup
        # =====================================================================
        # Cache SYCL JIT kernels across runs (big startup win — default is off).
        # Redirected into the data directory to keep it under user control.
        export SYCL_CACHE_PERSISTENT=1
        export SYCL_CACHE_DIR="$BASE_DIR/.cache/libsycl_cache"
        mkdir -p "$SYCL_CACHE_DIR"

        # Opt-in FP64 emulation for iGPUs without native double-precision hardware
        # (UHD 770, older Xe-LP). Off by default so discrete Arc surfaces real
        # errors instead of silently emulating. Users hitting "double precision
        # not supported" can export COMFY_ENABLE_XPU_FP64_EMULATION=1 before launch.
        if [[ "''${COMFY_ENABLE_XPU_FP64_EMULATION:-0}" == "1" ]]; then
          export OverrideDefaultFP64Settings=1
          export IGC_EnableDPEmulation=1
        fi
      ''}

            # Open browser if requested (background, after short delay)
            if [[ "$OPEN_BROWSER" == "true" ]]; then
              (sleep 3 && ${browserCommand} "http://127.0.0.1:$PORT" 2>/dev/null) &
            fi

            # Run ComfyUI directly from Nix store
            exec "${pythonRuntime}/bin/python" "${comfyuiSrc}/main.py" \
              --base-directory "$BASE_DIR" \
              --front-end-root "${frontendRoot}" \
              --database-url "sqlite:///$BASE_DIR/user/comfyui.db" \
              "''${COMFY_ARGS[@]}"
    '';
  };

  # Package wraps the launcher for installation
  comfyUiPackage = pkgs.stdenv.mkDerivation {
    pname = "comfy-ui";
    version = versions.comfyui.version;

    dontUnpack = true;
    dontBuild = true;
    dontConfigure = true;

    nativeBuildInputs = [ pkgs.makeWrapper ];

    installPhase = ''
      mkdir -p $out/bin
      ln -s ${comfyUiLauncher}/bin/comfy-ui $out/bin/comfy-ui
      ln -s $out/bin/comfy-ui $out/bin/comfyui
    '';

    passthru = {
      inherit
        comfyuiSrc
        pythonRuntime
        modelDownloaderDir
        frontendRoot
        ;
      version = versions.comfyui.version;
      # Expose heavy packages for Docker layer optimization
      # These are added to contents separately so buildLayeredImage creates distinct layers
      heavyDeps = [
        python.pkgs.torch
        python.pkgs.torchvision
        python.pkgs.torchaudio
        python.pkgs.transformers
        python.pkgs.numpy
        python.pkgs.pillow
        python.pkgs.scipy
        python.pkgs.opencv4
        python.pkgs.huggingface-hub
        python.pkgs.safetensors
        python.pkgs.accelerate
      ]
      ++ lib.optionals (python.pkgs ? xformers) [ python.pkgs.xformers ]
      ++ lib.optionals (python.pkgs ? bitsandbytes) [ python.pkgs.bitsandbytes ]
      ++ lib.optionals (python.pkgs ? triton) [ python.pkgs.triton ];
    };

    meta = with lib; {
      description = "ComfyUI - A powerful and modular diffusion model GUI";
      homepage = "https://github.com/Comfy-Org/ComfyUI";
      # ComfyUI is GPL-3.0; bundled custom nodes have various licenses
      license = with licenses; [
        gpl3 # ComfyUI, Impact Pack, KJNodes
        agpl3Only # bitsandbytes-NF4
        mit # rgthree-comfy, Florence2, MMAudio
        asl20 # GGUF, LTXVideo, x-flux, PuLID, WanVideoWrapper
      ];
      platforms = platforms.linux ++ platforms.darwin;
      maintainers = [
        {
          name = "James Brink";
          github = "utensils";
        }
      ];
      mainProgram = "comfy-ui";
    };
  };

  dockerLib = import ./docker.nix { inherit pkgs lib versions; };

  dockerImage = dockerLib.mkDockerImage {
    name = "comfy-ui";
    tag = "latest";
    comfyUiPackage = comfyUiPackage;
    extraLabels = {
      "org.opencontainers.image.version" = versions.comfyui.version;
    };
  };

  dockerImageCuda = dockerLib.mkDockerImage {
    inherit gpuSupport;
    name = "comfy-ui";
    tag = "cuda";
    comfyUiPackage = comfyUiPackage;
    cudaVersion = "cu128";
    extraLabels = {
      "org.opencontainers.image.version" = versions.comfyui.version;
      "com.nvidia.volumes.needed" = "nvidia_driver";
    };
  };

  dockerImageRocm = dockerLib.mkDockerImage {
    inherit gpuSupport;
    name = "comfy-ui";
    tag = "rocm";
    comfyUiPackage = comfyUiPackage;
    extraLabels = {
      "org.opencontainers.image.version" = versions.comfyui.version;
    };
  };

  dockerImageXpu = dockerLib.mkDockerImage {
    inherit gpuSupport;
    name = "comfy-ui";
    tag = "xpu";
    comfyUiPackage = comfyUiPackage;
    extraLabels = {
      "org.opencontainers.image.version" = versions.comfyui.version;
    };
  };
in
{
  default = comfyUiPackage;
  inherit
    dockerImage
    dockerImageCuda
    dockerImageRocm
    dockerImageXpu
    pythonRuntime
    comfyuiSrc
    modelDownloaderDir
    frontendRoot
    ;
}
